name: workflow-dragon

on:
    workflow_dispatch:
jobs:
    job-1:
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@v3

        - name: create a file
          run: |
            echo "hello world" > hello.txt
        
        - uses: actions/upload-artifact@v7
          with:
            name: my-hello-artifact
            path: hello.txt # Root path of the repo

    job-2:
      needs: job-1
      runs-on: ubuntu-latest
      steps:
      - name: download the artifact
        uses: actions/download-artifact@v7
        with:
            name: my-hello-artifact

      - name: read the filw
        run: |
            cat hello.txt
